### ISSUE TITLE
Does not work with Latest version

### ISSUE THREAD

**Issue by aswinthou** [razaqq/PotatoAlert#19]
The screen shows Red exclamation work with the words "Check Logs". It was working till yesterday 04-12-2020. And where is the logs folder? 

Is it due to API key expired?

**Comment by aswinthou** [comment]
Finally found the logs in Appdat/roaming I thought it would be in local. Anyway here is the log. BTW what is this perry-swift.de? Some webservice server for?

<pre>
2020-12-05 19:59:08 - ERROR:  404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
Traceback (most recent call last):
  File "potatoalert.py", line 132, in _run
  File "utils\central_api.py", line 15, in get_players
  File "aiohttp\client.py", line 1117, in __aenter__
  File "aiohttp\client.py", line 774, in _ws_connect
aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
2020-12-05 20:25:09 - ERROR:  404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
Traceback (most recent call last):
  File "potatoalert.py", line 132, in _run
  File "utils\central_api.py", line 15, in get_players
  File "aiohttp\client.py", line 1117, in __aenter__
  File "aiohttp\client.py", line 774, in _ws_connect
aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
2020-12-05 20:32:12 - ERROR:  404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
Traceback (most recent call last):
  File "potatoalert.py", line 132, in _run
  File "utils\central_api.py", line 15, in get_players
  File "aiohttp\client.py", line 1117, in __aenter__
  File "aiohttp\client.py", line 774, in _ws_connect
aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('ws://www.perry-swift.de:33333')
</pre>

**Comment by razaqq** [comment]
you have to update to the latest version
